### ISSUE TITLE
grails-geocode behind a proxy

### ISSUE THREAD

**Issue by sebDK** [domurtag/grails-geocode#1]
Hi there,

Is there any easy way to set a proxy for grails-geocode? It looks like now proxy is not handled by plugin:

```
 private initializeBuilder() {

        if (grailsApplication.config.geocode?.useHttp) {
            httpBuilder = new HTTPBuilder('http://maps.googleapis.com')
        }
    }
```

The solution I see is to add the following line:
`http.setProxy('proxy.com', 8080, 'http')`

Any help?

Thanks

**Comment by ghost** [comment]
Setting the HTTP proxy using system properties should work. If it doesn't please reopen this issue.
http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html
