### ISSUE TITLE
How to set the api key?

### ISSUE THREAD

**Issue by danielfigueroaj** [domurtag/grails-geocode#3]
Thanks in advanced

**Comment by ghost** [comment]
You should be able to provide the API key within the `Map` of optional arguments, e.g.
```groovy
geocodingService.getPoints('Birmingham', [key: 'YOUR_API_KEY')
```

**Comment by danielfigueroaj** [comment]
thank you, I'm sorry,  i read again the documentation, and the answer was already there.
